version: "2"

linters:
  enable:
    - contextcheck
    - gocritic
    - gosec
    - misspell
    - modernize
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/k8s-driver-manager
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
